# 1. Import Dependencies

In [1]:
import gym
from gym import Env
from gym.spaces import Discrete, Box, Dict, Tuple, MultiBinary, MultiDiscrete

import numpy as np
import random
import os

from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.evaluation import evaluate_policy

# 2. Types of Spaces

In [2]:
Discrete(2).sample()

1

In [3]:
Box(0,1, shape=(3,)).sample()

array([0.513801  , 0.79194844, 0.5833182 ], dtype=float32)

In [5]:
Tuple( (Discrete(3), Box(0,1, shape=(3,)))).sample()

(2, array([0.07008628, 0.18942754, 0.59361196], dtype=float32))

In [6]:
Dict({'height':Discrete(2), 'speed':Box(0,100, shape=(1,))}).sample()

OrderedDict([('height', 0), ('speed', array([54.55228], dtype=float32))])

In [7]:
MultiBinary(4).sample()

array([0, 1, 1, 0], dtype=int8)

In [8]:
MultiDiscrete([5,2,2,5]).sample()

array([4, 0, 1, 1], dtype=int64)

# 3. Building an Environment
- Build an agent to give us the best shower possible
- Randomly temperature
- 37 and 39 degC

# 4. Test Environment 

# 5. Train Model 

# 6. Save Model